# -*- coding: utf-8 -*-
"""Ārati songs (Reader v7.4): two chapters in Part IV «Праздники, обеты и песни арати».

Satkirti 07.10.2026 13:07: «И включи песни мангала-арати и гаура-арати, чтобы были в
обновлённой версии сейчас».

Source: pesni_arati.json = the draft «Песни арати» 07.10.2026 (…/Черновики/2026-10-07 Песни арати,
парампара, прамана/_исходники/pesni_arati.json), copied here unchanged. Nothing is generated by a
model in this script: IAST, word-by-word and translation are taken from the draft as they are.
  * RU (book.ru-iast.json): IAST + пословный перевод + перевод + source line.
  * RU Cyrillic mirror (book.ru.json): the same, Sanskrit transliterated (scripts/translate/iast_to_cyrillic.py).
  * EN (book.json): IAST only + title/author in IAST — the draft has no English translation
    (the GVP English text is not in the draft) — open question for Satkirti/Gurudas.
Since v7.5 (Satkirti 07.10 16:05) NO source line is shown in the book; source_line() keeps it internal: the draft's «source» (bibliography); for song 3 also the credit of the
published Russian translation (first sentence of its «translation_source»). The draft's working notes
about who made the other translations («Липикара … модель …; требует проверки») stay in the draft.

    python scripts/chapters/ch16_arati_songs/build.py     (idempotent)
"""
import copy
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")
CH = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(CH, "..", "..", ".."))
DATA = os.path.join(REPO, "data")
sys.path.insert(0, os.path.join(REPO, "scripts", "translate"))
from iast_to_cyrillic import translit  # noqa: E402

PART_ID = "festivals-vows"
AFTER = "major-festivals"
CHAPTERS = [  # id, draft «part», RU title, EN title, subsection id per song_no
    ("mangala-arati-songs", "Мангала-арати", "Песни мангала-арати", "Maṅgala-ārati Songs",
     {1: "song-gurvastakam", 2: "song-prabhupada-padma-stavakah", 3: "song-mangala-arati",
      4: "song-vibhavari-sesa", 5: "song-vraja-dhama-mahimamrta"}),
    ("gaura-arati-songs", "Гаура-арати (вечернее арати)", "Песни гаура-арати", "Gaura-ārati Songs",
     {6: "song-gaura-arati", 7: "song-yugala-arati"}),
]
OTHER = ["lv", "de", "fr", "es", "it", "uk", "hu"]
FILES = {"en": "book.json", "ru": "book.ru.json", "ru-iast": "book.ru-iast.json"}


# Book standard (05.10.2026, Satkirti; qa L1): in a pair of Deity names only the last part is declined —
# «Радха-Кришны». The published 2004 translation of song 3 has «Радхи-Кришны»; corrected here, and the
# credit line says so (rule «ошибки в присланном тексте исправляем и коротко говорим, что исправили»).
NORMALIZE = {"Шри Шри Радхи-Кришны": "Шри Шри Радха-Кришны"}


def norm(text):
    for a, b in NORMALIZE.items():
        text = text.replace(a, b)
    return text


def source_line(song):
    line = song["source"].strip()
    tr = song.get("translation_source", "")
    if tr.startswith("Литературный перевод — опубликованный русский перевод"):
        credit = tr.split(" Пословный перевод")[0].strip()
        if any(a in v["translation"] for v in song["verses"] for a in NORMALIZE):
            credit = credit.replace("(дословно).", "(дословно; склонение пары имён Божеств — по стандарту книги: «Шри Шри Радха-Кришны»).")
        line += "\n" + credit
    return line


# Song header (Reader v7.5, Satkirti 07.10.2026 16:05): the heading (subsection title, in Russian),
# then ONE line — the author — then the verses. No repeated IAST title line, and no source /
# bibliography line under a song: the sources stay internal (source_line(), pesni_arati.json).
def song_ru(song):
    return [{"type": "text", "content": song["author"]}] + \
           [{"type": "verse", "sanskrit": v["sanskrit"], "wbw": v["wbw"], "translation": norm(v["translation"])}
            for v in song["verses"]]


def song_en(song):
    return [{"type": "text", "content": f"⟦{song['author_iast']}⟧"}] + \
           [{"type": "verse", "sanskrit": v["sanskrit"]} for v in song["verses"]]


def wbw_cyr(wbw):
    out = []
    for part in wbw.split("; "):
        m = re.match(r"^(.*?)( — .*)$", part)
        out.append(translit(m.group(1)) + m.group(2) if m else translit(part))
    return "; ".join(out)


def to_cyr(sec):
    s = copy.deepcopy(sec)
    for sub in s["subsections"]:
        for b in sub["content"]:
            if b["type"] == "verse":
                b["sanskrit"] = translit(b["sanskrit"])
                if b.get("wbw"):
                    b["wbw"] = wbw_cyr(b["wbw"])
            elif b["type"] == "text":
                b["content"] = re.sub(r"⟦([^⟦⟧]*)⟧", lambda m: "⟦" + translit(m.group(1)) + "⟧", b["content"])
    return s


def sections(songs, lang):
    out = []
    for sid, part, ru_t, en_t, subs in CHAPTERS:
        group = [s for s in songs if s["part"] == part]
        assert [s["song_no"] for s in group] == list(subs), (part, [s["song_no"] for s in group])
        out.append({
            "id": sid, "title": en_t if lang == "en" else ru_t, "subtitle": None, "page": "",
            "content": [],
            "subsections": [{"id": subs[s["song_no"]], "title": s["title_iast"] if lang == "en" else s["title"],
                             "content": song_en(s) if lang == "en" else song_ru(s)} for s in group],
        })
    return [to_cyr(s) for s in out] if lang == "ru" else out


def write_json(path, obj):
    raw = open(path, encoding="utf-8", newline="").read()
    nl = "\n" if raw.endswith("\n") else ""
    open(path, "w", encoding="utf-8", newline="").write(json.dumps(obj, ensure_ascii=False, indent=2) + nl)


def main():
    songs = json.load(open(os.path.join(CH, "pesni_arati.json"), encoding="utf-8"))
    ids = [c[0] for c in CHAPTERS]
    for lang in ["en", "ru", "ru-iast"] + OTHER:
        path = os.path.join(DATA, FILES.get(lang, f"book.{lang}.json"))
        book = json.load(open(path, encoding="utf-8"))
        if lang in FILES:
            book["sections"] = [s for s in book["sections"] if s["id"] not in ids]
            at = [s["id"] for s in book["sections"]].index(AFTER) + 1
            book["sections"][at:at] = sections(songs, lang)
        p = next(x for x in book["parts"] if x["id"] == PART_ID)
        p["sections"] = [x for x in p["sections"] if x not in ids]
        at = p["sections"].index(AFTER) + 1 if AFTER in p["sections"] else len(p["sections"])
        p["sections"][at:at] = ids
        write_json(path, book)
        print("wrote", lang, p["sections"])


if __name__ == "__main__":
    main()
