# -*- coding: utf-8 -*-
"""Kārtika bhajans (Reader v7.6): chapter «Бхаджаны для Картики» in Part IV «Праздники, обеты и песни арати»,
right after «Песни гаура-арати».

Source: kartika_bhajany.json = the draft «Бхаджаны Картики» 07.10.2026
(…/Арчана-паддхати — книга/Черновики/2026-10-07 Бхаджаны Картики/kartika_bhajany.json), copied here unchanged.
It already holds the chapter as book sections: key «ru-iast» (book.ru-iast.json) and «en» (book.json).
Nothing is generated by a model in this script.
  * Шри Дамодараштака (8), Шри Нанда-нанданаштака (9), Шри Радха-крипа-катакша-става-раджа (13 — GVP).
  * Song format (Satkirti 07.10.2026 16:05, lint L24): Russian heading, ONE author line, then IAST verses
    (пословно / перевод); no source lines (sources stay in the draft's «Источники.md»), no repeated IAST title.
  * RU Cyrillic mirror (book.ru.json): the same, Sanskrit transliterated (scripts/translate/iast_to_cyrillic.py),
    exactly as ch16_arati_songs does.
  * Since v7.7 (Satkirti 07.10.2026 18:55: «Можно перевод брать отсюда») the RU «перевод» of all 3 songs (30 verses)
    is the published Russian translation, verbatim: «Песенник гаудия-вайшнава», Воронеж, 2015 (compiled from
    «Шри Гаудия-гити-гуччха», GVP, Russian ed. 2010; …/Библиотека/Гаудия Веданта (Нараяна Махарадж)/), PDF pages:
    Дамодараштака 319–321, Нанда-нанданаштака 352–353, Радха-крипа-катакша 353–357; verse counts/order 1:1
    (8/9/13). Edit: dash « – » → « — » (book typography). IAST unchanged (GVP); the songbook's transliteration is
    not used. Word-by-word ours; RKK 7 «Мана-мохане» → «Мадана-мохане» (as in the songbook). EN unchanged.
    Details: …/Черновики/2026-10-07 Бхаджаны Картики/Источники.md and «Переводы из песенника — сверка.md».
  * Other languages (lv, de, fr, es, it, uk, hu): only the chapter id in the part list — the app shows the
    English section as fallback (lib/content.ts) until the night translation run adds them.

    python scripts/chapters/ch17_kartika_bhajans/build.py     (idempotent)
"""
import copy
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")
CH = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(CH, "..", "..", ".."))
DATA = os.path.join(REPO, "data")
sys.path.insert(0, os.path.join(REPO, "scripts", "translate"))
from iast_to_cyrillic import translit  # noqa: E402

PART_ID = "festivals-vows"
AFTER = "gaura-arati-songs"
SID = "kartika-bhajans"
SONGS = {"song-damodarastakam": 8, "song-nanda-nandanastakam": 9, "song-radha-krpa-kataksa-stava-raja": 13}
OTHER = ["lv", "de", "fr", "es", "it", "uk", "hu"]
FILES = {"en": "book.json", "ru": "book.ru.json", "ru-iast": "book.ru-iast.json"}


def wbw_cyr(wbw):
    out = []
    for part in wbw.split("; "):
        m = re.match(r"^(.*?)( — .*)$", part)
        out.append(translit(m.group(1)) + m.group(2) if m else translit(part))
    return "; ".join(out)


def to_cyr(sec):
    s = copy.deepcopy(sec)
    for sub in s["subsections"]:
        for b in sub["content"]:
            if b["type"] == "verse":
                b["sanskrit"] = translit(b["sanskrit"])
                if b.get("wbw"):
                    b["wbw"] = wbw_cyr(b["wbw"])
            elif b["type"] == "text":
                b["content"] = re.sub(r"⟦([^⟦⟧]*)⟧", lambda m: "⟦" + translit(m.group(1)) + "⟧", b["content"])
    return s


def check(sec):
    assert sec["id"] == SID, sec["id"]
    got = {sub["id"]: sum(1 for b in sub["content"] if b["type"] == "verse") for sub in sec["subsections"]}
    assert got == SONGS, got
    for sub in sec["subsections"]:
        c = sub["content"]
        assert c[0]["type"] == "text" and all(b["type"] == "verse" for b in c[1:]), sub["id"]
        assert all(b.get("wbw") and b.get("translation") for b in c[1:]), sub["id"]


def section(draft, lang):
    sec = copy.deepcopy(draft["en" if lang == "en" else "ru-iast"])
    check(sec)
    return to_cyr(sec) if lang == "ru" else sec


def write_json(path, obj):
    raw = open(path, encoding="utf-8", newline="").read()
    nl = "\n" if raw.endswith("\n") else ""
    open(path, "w", encoding="utf-8", newline="").write(json.dumps(obj, ensure_ascii=False, indent=2) + nl)


def main():
    draft = json.load(open(os.path.join(CH, "kartika_bhajany.json"), encoding="utf-8"))
    for lang in ["en", "ru", "ru-iast"] + OTHER:
        path = os.path.join(DATA, FILES.get(lang, f"book.{lang}.json"))
        book = json.load(open(path, encoding="utf-8"))
        if lang in FILES:
            book["sections"] = [s for s in book["sections"] if s["id"] != SID]
            at = [s["id"] for s in book["sections"]].index(AFTER) + 1
            book["sections"][at:at] = [section(draft, lang)]
        p = next(x for x in book["parts"] if x["id"] == PART_ID)
        p["sections"] = [x for x in p["sections"] if x != SID]
        at = p["sections"].index(AFTER) + 1 if AFTER in p["sections"] else len(p["sections"])
        p["sections"][at:at] = [SID]
        write_json(path, book)
        print("wrote", lang, p["sections"])


if __name__ == "__main__":
    main()
